services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - "./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
      - "./db-data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=${MONGO_DB:-db}
      - MONGO_INITDB_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_PASSWORD=$MONGO_PASSWORD

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://$MONGO_ROOT_USERNAME:$MONGO_ROOT_PASSWORD@mongo:${MONGO_PORT:-27017}/
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_EXPRESS_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_EXPRESS_PASSWORD
    depends_on:
      - mongo