# Next.JS run next dev --turbopack

FROM node:20-alpine

WORKDIR /app

COPY package.json .

RUN npm i

# all *config.mjs *config.js *config.ts *config.json
COPY *config.mjs *config.js *config.ts *config.json .env* ./

COPY .licenses .

COPY public ./public
COPY src ./src


CMD ["npm", "run", "dev"]

