services:
  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - minio
      - redis
    restart: always
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
      - .env.local
    expose:
      - 3000
    networks:
      - default
      # - public

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - "./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
      - "./data/db:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=${MONGO_DB:-db}
      - MONGO_INITDB_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_PASSWORD=$MONGO_PASSWORD
    expose:
      - 27017
    networks:
      - default

  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: always
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_DASHBOARD_PORT:-9001}:9001"
    volumes:
      - "./data/obj:/data"
    expose:
      - 9000
      - 9001
    networks:
      - default
    command: server /data --console-address ":9001"

  minio-setup:
    container_name: minio-setup
    image: minio/mc
    restart: "no"
    depends_on:
      - minio
    env_file:
      - .env
      - .env.local
    volumes:
      - "./minio-init.sh:/minio-init.sh:ro"
    networks:
      - default
    entrypoint: /bin/sh /minio-init.sh

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379
    networks:
      - default
    # Disable appendonly mode since this is only for session storage
    command: redis-server --appendonly no --requirepass $REDIS_PASSWORD

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./certs:/etc/ssl/certs:ro"
      - "./logs/nginx:/var/log/nginx" # For logging
    environment:
      - NGINX_PORT=${NGINX_PORT:-80}
      - NGINX_SSL_PORT=${NGINX_SSL_PORT:-443}
      - BACKEND_HOST=${BACKEND_HOST:-host.docker.internal}
    expose:
      - ${NGINX_PORT:-80}
    networks:
      - default

networks:
  default:
    driver: bridge
  # public:
  #   enable_ipv6: true
  #   ipam:
  #     config:
  #       - subnet: 2406:da18:99:2902::/64
  #         ip_range: 2406:da18:99:2902::/64
  #         gateway: 2406:da18:99:2902::1