# Next.JS run next dev --turbopack

FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

# all *config.mjs *config.js *config.ts *config.json
COPY *config.mjs *config.js *config.ts *config.json .licenses public src ./

CMD ["npm", "run", "dev"]

